### ISSUE TITLE
This isn't an issue but..

### ISSUE THREAD

**Issue by invokes** [charliea21/RCL#1]
Hey man I was wondering if you could explain to me how the cookie logger works?
My discord - invoke#2700
Thank you!

**Comment by charliea21** [comment]
Hi, this repo is just a Roblox Cookie logger, it’s for educational purposes e.g learning how it works etc.

The app must be open before Roblox is opened. Once it detects Roblox has been opened, it grabs the fifth flag from the RobloxPlayerBeta.exe arguments. It then makes a web request and passes the flag as the authentication ticket. The web request then contains the .ROBLOSECURITY cookie in the Set-Cookie header.

**Comment by invokes** [comment]
how do i view/grab the flag

**Comment by invokes** [comment]
how do i view/grab the flag
